import 'dotenv/config';
import mongoose from 'mongoose';
import bcrypt from 'bcryptjs';
import SuperAdmin from '../models/SuperAdmin.js';
import School from '../models/School.js';
import Librarian from '../models/Librarian.js';
import Book from '../models/Book.js';
import Student from '../models/Student.js';
import Teacher from '../models/Teacher.js';
import BookAllocation from '../models/BookAllocation.js';

const booksData = [
  { title: 'HTML', author: 'GOAL KICKER', category: 'programming', isbn: 'swd html 001' },
  { title: 'MYSQL', author: 'GOAL KICKER', category: 'PROGRAMMING', isbn: 'swd mysql 001' },
  { title: 'PHP AND MYSQL', author: 'LARRY ULMAN', category: 'PROGRAMMING', isbn: 'swd php&amp;mysql 001' },
  { title: 'JAVASCRIPT PROGRAMMING', author: 'GOAL KICKER', category: 'PROGRAMMING', isbn: 'SWD JS 001' },
  { title: 'SQL', author: 'HANS-PETER HALVORSEN', category: 'PROGRAMMING', isbn: 'SWD SQL 001' },
  { title: 'XHTML', author: 'LAKSHMI PRAYAGA', category: 'PROGRAMMING', isbn: 'SWD HTML 002' },
  { title: 'THTML', author: 'IAN LIOD', category: 'PROGRAMMING', isbn: 'SWD HTML 003' },
  { title: 'THTML', author: 'IAN LIOD', category: 'PROGRAMMING', isbn: 'SWD HTML 003' },
  { title: 'THTML', author: 'IAN LIOD', category: 'PROGRAMMING', isbn: 'SWD HTML 003' },
  { title: 'THTML', author: 'IAN LIOD', category: 'PROGRAMMING', isbn: 'SWD HTML 003' },
  { title: 'THTML', author: 'IAN LIOD', category: 'PROGRAMMING', isbn: 'SWD HTML 003' },
  { title: 'THTML', author: 'IAN LIOD', category: 'PROGRAMMING', isbn: 'SWD HTML 003' },
  { title: 'THTML', author: 'IAN LIOD', category: 'PROGRAMMING', isbn: 'SWD HTML 003' },
  { title: 'DATABASE', author: 'MICHAEL KOFLER', category: 'PROGRAMMING', isbn: 'SWD DATABASE 001' },
  { title: 'DATABASE', author: 'MICHAEL KOFLER', category: 'PROGRAMMING', isbn: 'SWD DATABASE 002' },
  { title: 'DATABASE', author: 'MICHAEL KOFLER', category: 'PROGRAMMING', isbn: 'SWD DATABASE 005' },
  { title: 'DATABASE', author: 'MICHAEL KOFLER', category: 'PROGRAMMING', isbn: 'SWD DATABASE 003' },
  { title: 'DATABASE', author: 'MICHAEL KOFLER', category: 'PROGRAMMING', isbn: 'SWD DATABASE 007' },
  { title: 'DATABASE', author: 'MICHAEL KOFLER', category: 'PROGRAMMING', isbn: 'SWD DATABASE 006' },
  { title: 'DATABASE', author: 'MICHAEL KOFLER', category: 'PROGRAMMING', isbn: 'SWD DATABASE 004' },
  { title: 'DATABASE', author: 'MICHAEL KOFLER', category: 'PROGRAMMING', isbn: 'SWD DATABASE 004' },
  { title: 'DATABASE', author: 'MICHAEL KOFLER', category: 'PROGRAMMING', isbn: 'SWD DATABASE 008' },
  { title: 'DATABASE', author: 'MICHAEL KOFLER', category: 'PROGRAMMING', isbn: 'SWD DATABASE 009' },
  { title: 'DATA MANAGEMENT DATABASES AND ORGANIZATION', author: 'RICHARD T. WATSON', category: 'PROGRAMMING', isbn: 'SWD DATA MANAGEMENT DB 002' },
  { title: 'DATA MANAGEMENT DATABASE AND ORGANIZATION', author: 'RICHARD T. WATSON', category: 'PROGRAMMING', isbn: 'SWD DATA MANAGEMENT DB 002' },
  { title: 'KEYBOARDING', author: 'SCOT OBER', category: 'KEYBOARDING', isbn: 'SWD KEYBOARD DOCUMENTING 002' },
  { title: 'KEYBOARDING', author: 'SCOT OBER', category: 'KEYBOARDING', isbn: 'SWD KEYBOARD DOCUMENTING 001' },
  { title: 'KEYBOARDING', author: 'SCOT OBER', category: 'KEYBOARDING', isbn: 'SWD KEYBOARD DOCUMENTING 001' },
  { title: 'KEYBOARDING', author: 'SCOT OBER', category: 'KEYBOARDING', isbn: 'SWD KEYBOARD DOCUMENTING 003' },
  { title: 'KEYBOARDING', author: 'SCOT OBER', category: 'KEYBOARDING', isbn: 'SWD KEYBOARD DOCUMENTING 003' },
  { title: 'MICROSOFT OFFICE', author: 'MICHAEL HALVORSON', category: 'KEYBOARDING', isbn: 'SWD MICROSOFT OFFICE XP 001' },
  { title: 'COBOL PROGRAMMING', author: 'NANCY STERN', category: 'PROGRAMMING', isbn: '0-471-29987-1' },
  { title: 'POWER POINT', author: 'MICHAEL SPRINGER', category: 'COMPUTER SKILLS', isbn: '1-4260-9768-9' },
  { title: 'MICROSOFT OFFICE OUTLOOK FOR WINDOWS', author: 'JIM BOYCE', category: 'COMPUTER SKILLS', isbn: '0-321-20041-1' },
  { title: 'INTEGRATING TECHNOLOGY IN CONNECTED WORLD', author: 'GARY B. SHELLY', category: 'COMPUTER SKILLS', isbn: '978-1-133-52655-1' },
  { title: 'DIGITAL WORLD', author: 'JON GORDON', category: 'COMPUTER SKILLS', isbn: '978-0-76384-756-2' },
  { title: 'ADOBE PHTOSHOP', author: 'ADOBE COMPANY', category: 'GRAPHICH DESIGN', isbn: 'MMP ADOBE PHOTOSHOP 001' },
  { title: 'GRAPHIC DESIGN 6 IN BASICS', author: 'AMY E. ARNTSON', category: 'GRAPHIC DESIGN', isbn: 'MMP GRAPHIC DESIGN 001' },
  { title: 'GRAPHIC DESIGN 6 IN BASICS', author: 'AMY E. ARNTSON', category: 'GRAPHIC DESIGN', isbn: 'MMP GRAPHIC DESIGN 001' },
  { title: 'VIDEO PRODUCTION HANDBOOK', author: 'GERALD MILLERSON', category: 'VIDEO PRODUCTION', isbn: 'MMP VIDEO PRODUCTION 001' },
  { title: 'CINEMATOGRAPHY', author: 'JOSEPH V. MASCELLLI', category: 'VIDEO PRODUCTION', isbn: 'MMP CINEMATOGRAPHY 001' },
  { title: 'GRAMMAR OF EDIT', author: 'ROY TOMPSON', category: 'EDITING', isbn: 'MMP GRAMMAR OF EDIT 001' },
  { title: 'GRAMMAR OF EDIT', author: 'ROY TOMPSON', category: 'VIDEO PRODUCTION', isbn: 'MMP GRAMMAR OF EDIT 001' },
  { title: 'DESIGN POTIFOLIO', author: 'CYNTHIA L. BARON', category: 'GRAPHIC DESIGN', isbn: 'MMP DESIGN PORTIFLIO 001' },
  { title: 'DIGITAL RADIO PRODUCTION', author: 'DONALD CONNELLY', category: 'RADIO PRODUCTION', isbn: 'MMP DIGITAL RADION PRODUCTION 001' },
  { title: 'DIGITAL RADIO PRODUCTION', author: 'DONALD CONNELLY', category: 'RADIO PRODUCTION', isbn: 'MMP DIGITAL RADION PRODUCTION 002' },
  { title: 'DIGITAL RADIO PRODUCTION', author: 'DONALD CONNELLY', category: 'RADIO PRODUCTION', isbn: 'MMP DIGITAL RADION PRODUCTION 003' },
  { title: 'C PROGRAMMING', author: 'KLAUS SCHRODER', category: 'PROGRAMMING', isbn: 'CSA C PROGRAMMING 001' },
  { title: 'C PROGRAMMING', author: 'KLAUS SCHRODER', category: 'PROGRAMMING', isbn: 'CSA C PROGRAMMING 002' },
  { title: 'C PROGRAMMING', author: 'KLAUS SCHRODER', category: 'PROGRAMMING', isbn: 'CSA C PROGRAMMING 003' },
  { title: 'C PROGRAMMING', author: 'KLAUS SCHRODER', category: 'PROGRAMMING', isbn: 'CSA C PROGRAMMING 004' },
  { title: 'C PROGRAMMING', author: 'KLAUS SCHRODER', category: 'PROGRAMMING', isbn: 'CSA C PROGRAMMING 005' },
  { title: 'C++', author: 'ROB MC GREGOR', category: 'PROGRAMMING', isbn: 'CSA C++ 001' },
  { title: 'C++', author: 'ROB MC GREGOR', category: 'PROGRAMMING', isbn: 'CSA C++ 002' },
  { title: 'C++', author: 'ROB MC GREGOR', category: 'PROGRAMMING', isbn: 'CSA C++ 003' },
  { title: 'C++', author: 'ROB MC GREGOR', category: 'PROGRAMMING', isbn: 'CSA C++ 004' },
  { title: 'C++', author: 'ROB MC GREGOR', category: 'PROGRAMMING', isbn: 'CSA C++ 005' },
  { title: 'LEARN C PROGRAMMING', author: 'TUTORIALS POINT', category: 'PROGRAMMING', isbn: 'CSA C PROGRAMMING  006' },
  { title: 'COMPUTER SCIENCE', author: 'HERMAN ODUOR', category: 'COMPUTER SCIENCE', isbn: 'CSA COMP SCIENCE 001' },
  { title: 'COMPUTER SCIENCE', author: 'HERMAN ODUOR', category: 'COMPUTER SCIENCE', isbn: 'CSA COMP SCIENCE 002' },
  { title: 'COMPUTER STUDIES', author: 'ISAAC K. KIWANUKA', category: 'COMPUTER STUDIES', isbn: 'CSA COMP STUDIES 001' },
  { title: 'COMPUTER STUDIES', author: 'ISAAC K. KIWANUKA', category: 'COMPUTER STUDIES', isbn: 'CSA COMP STUDIES 002' },
  { title: 'COMPUTER STUDIES', author: 'ISAAC K. KIWANUKA', category: 'COMPUTER STUDIES', isbn: 'CSA COMP STUDIES 003' },
  { title: 'COMPUTER STUDIES', author: 'ISAAC K. KIWANUKA', category: 'COMPUTER STUDIES', isbn: 'CSA COMP STUDIES 004' },
  { title: 'COMPUTER STUDIES', author: 'ISAAC K. KIWANUKA', category: 'COMPUTER STUDIES', isbn: 'CSA COMP STUDIES 005' },
  { title: 'COMPUTER STUDIES', author: 'ISAAC K. KIWANUKA', category: 'COMPUTER STUDIES', isbn: '978-9970-19-092-8' },
  { title: 'OPERATING SYSTEM', author: 'HARSH BHOR', category: 'COMPUTER SKILLS', isbn: 'CSA OS 001' },
  { title: 'OPERATING SYSTEM', author: 'HARSH BHOR', category: 'COMPUTER SKILLS', isbn: 'CSA OS 002' },
  { title: 'OPERATING SYSTEM', author: 'HARSH BHOR', category: 'COMPUTER SKILLS', isbn: 'CSA OS 003' },
  { title: 'OPERATING SYSTEM', author: 'HARSH BHOR', category: 'COMPUTER SKILLS', isbn: 'CSA OS 004' },
  { title: 'OPERATING SYSTEM', author: 'HARSH BHOR', category: 'COMPUTER SKILLS', isbn: 'CSA OS 005' },
  { title: 'COMPUTER STUDIES', author: 'S. MBURU G CHEMWA', category: 'COMPUTER STUDIES', isbn: 'CSA COMP STUDIES 006' },
  { title: 'COMPUTER STUDIES', author: 'S. MBURU G CHEMWA', category: 'COMPUTER STUDIES', isbn: 'CSA COMP STUDIES 007' },
  { title: 'COMPUTER STUDIES', author: 'S. MBURU G CHEMWA', category: 'COMPUTER STUDIES', isbn: 'CSA COMP STUDIES 008' },
  { title: 'MICROSOFT INTERPRETER', author: 'MICROSOFT', category: 'COMPUTER SKILLS', isbn: 'CSA G-W BASIC 001' },
  { title: 'WINDOW VISTA', author: 'JEAN ANDREWS', category: 'COMPUTER SKILLS', isbn: '978-1-4239-0216-4' },
  { title: 'COMPUTER-AIDED MAINTAINANCE', author: 'JAY LEE', category: 'COMPUTER SKILLS', isbn: '978-146-1-4613-7421-3' },
  { title: 'COMPUTER HARDWARE MAINTENANCE', author: 'STEPHEN C. ROOD', category: 'COMPUTER SKILLS', isbn: '0-7506-9494-7' },
  { title: 'COMPUTER CONFLUENCE', author: 'GEORGE BECKMAN', category: 'COMPUTER SKILLS', isbn: '0-201-42881-4' },
  { title: 'REPAIRING HARDWARE', author: 'NONE', category: 'COMPUTER SKILLS', isbn: 'CSA REPAIRING HARDWARE 001' },
  { title: 'PERSONAL COMPUTER', author: 'SHARP CORPORATION', category: 'COMPUTER SKILLS', isbn: 'CSA PC 001' },
  { title: 'INFORMATION TECHNOLOGY', author: 'NDUWINGOMA MATHIAS', category: 'IT', isbn: 'CSA IT 001' },
  { title: 'INFORMATION TECHNOLOGY', author: 'NDUWINGOMA MATHIAS', category: 'IT', isbn: 'CSA IT 002' },
  { title: 'INFORMATION TECHNOLOGY', author: 'NDUWINGOMA MATHIAS', category: 'IT', isbn: 'CSA IT 003' },
  { title: 'ELECTRICAL INSTALLATION', author: 'DAVID ALLAN', category: 'ELECTRICITY', isbn: 'ELT ELECTRICAL INSTALL 001' },
  { title: 'ELECTRICAL INSTALLATION', author: 'DAVID ALLAN', category: 'ELECTRICITY', isbn: 'ELT ELECTRICAL INSTALL 002' },
  { title: 'MOTOR VEHICLE ENGINEERING', author: 'DEREK NEWBOLD', category: 'ELECTRICITY', isbn: 'ELT MV ENGINEERING 001' },
  { title: 'MOTOR VEHICLE ENGINEERING', author: 'DEREK NEWBOLD', category: 'ELECTRICITY', isbn: 'ELT MV ENGINEERING 002' },
  { title: 'MOTOR VEHICLE ENGINEERING', author: 'DEREK NEWBOLD', category: 'ELECTRICITY', isbn: 'ELT MV ENGINEERING 003' },
  { title: 'electricity', author: 'stephen l.herman', category: 'ELECTRICITY', isbn: '978-1-285-85270-6' },
  { title: 'BASIC EEEP', author: 'JOHN BIRD', category: 'ELECTRICITY', isbn: 'ELT EEPT 001' },
  { title: 'BASIC EEEP', author: 'JOHN BIRD', category: 'ELECTRICITY', isbn: 'ETE EEPT 002' },
  { title: 'MOTIVATE ELECTRICAL INSTALLATION PRINCIPLES AND PRACTICES', author: 'J.M.HYDE', category: 'ELECTRICITY', isbn: 'ELT MOTIVATE INSTALLATION PP 001' },
  { title: 'MOTIVATE ELECTRICAL INSTALLATION PRINCIPLES AND PRACTICES', author: 'J.M.HYDE', category: 'ELECTRICITY', isbn: 'ELT MOTIVATE INSTALLATION PP 002' },
  { title: 'PRACTICAL ELECTRICITY AND ELECTRONICS', author: 'JOHN WATSON', category: 'ELECTRICITY', isbn: 'ELT MOTIVATE PRACTICE 002' },
  { title: 'ELECTRICAL INSTALLATION CALCULATION', author: 'A.J WATKINS', category: 'ELECTRICITY', isbn: 'ELT INSTALL-CALC 001' },
  { title: 'ELECTRICAL INSTALLATION', author: 'MAURICE LEWIS', category: 'ELECTRICITY', isbn: 'ELT MOTIVATE INSTALLATION 001' },
  { title: 'ELECTRICAL INSTALLATION', author: 'MAURICE LEWIS', category: 'ELECTRICITY', isbn: 'ELT MOTIVATE INSTALLATION 002' },
  { title: 'ELECTRICAL INSTALLATION', author: 'MAURICE LEWIS', category: 'ELECTRICITY', isbn: 'ELT MOTIVATE INSTALLATION 003' },
  { title: 'PRACTICAL ELECTRICITY AND ELECTRONICS', author: 'JOHN WATSON', category: 'ELECTRICITY', isbn: 'ELT MOTIVATE PRACTICE 001' },
  { title: 'MOTOR VIHICLE TECHNOLOGY FOR MECHANICS', author: 'P P J READ', category: 'ELECTRICITY', isbn: '0-333-60159-9' },
  { title: 'METAL WORK TECHNOLOGY', author: 'J.K.N SACKEY', category: 'ELECTRICITY', isbn: '0-333-60054-1' },
  { title: 'PRACTICAL WELDING', author: 'STUART W. GIBSON', category: 'ELECTRICITY', isbn: '0-333-60957-3' },
  { title: 'TECHNICAL DRAWING WITH DESIGN', author: 'A. YARWOOD', category: 'ELECTRICITY', isbn: '0-333-60161-0' },
  { title: 'ELECTRICAL INSTALLATION PRINCIPLES AND PRACTICE', author: 'J.M.HYDE', category: 'ELECTRICITY', isbn: '0-333-60160-2' },
  { title: 'ELECTRICAL INSTALLATION PRINCIPLES AND PRACTICE', author: 'J.M.HYDE', category: 'ELECTRICITY', isbn: '0-333-60160-2' },
  { title: 'ELECTRICAL INSTALLATION PRINCIPLES AND PRACTICE', author: 'J.M.HYDE', category: 'ELECTRICITY', isbn: 'ELT MOTIVATE INSTALLATION PP 003' },
  { title: 'ELECTRICAL CABLES HANDBOOK', author: 'G. F. MOORE', category: 'ELECTRICITY', isbn: '978-0-632-04075-9' },
  { title: 'ELECTRICAL CABLES HANDBOOK', author: 'G. F. MOORE', category: 'ELECTRICITY', isbn: '978-0-632-04075-9' },
  { title: 'PRACTICAL ELECTRICITY AND ELECTRONICS', author: 'JOHN WATSON', category: 'ELECTRICITY', isbn: 'ELT MOTIVATE PRACTICE 003' },
  { title: 'BASIC ELECTRICAL INSTALLLATION WORK', author: 'TREVOR LINSLEY', category: 'ELECTRICITY', isbn: 'ELT INSTALL 001' },
  { title: 'ELECTRICAL INSTALLATIION PRINCIPLES AND PRACTICES', author: 'J.M.HYDE', category: 'ELECTRICITY', isbn: 'ELT MOTIVATE INSTALLATION PP 003' },
  { title: 'ELECTRICAL INSTALLATION CALCULATIONS', author: 'A.J WATKINS', category: 'ELECTRICITY', isbn: '0-340-73185-0' },
  { title: 'FLUID POWER WITH APPLICATIONS', author: 'ANTHONY ESPOSITO', category: 'ELECTRICITY', isbn: '0-13-060899-8' },
  { title: 'BASIC ELECTRICAL INSTALLATION WORK', author: 'TREVOR LINSLEY', category: 'ELECTRICITY', isbn: '0-340-70574-4' },
  { title: 'ADVANCED ELECTRICAL INSTALLATION WORK', author: 'TREVOR LINSLEY', category: 'ELECTRICITY', isbn: '0-340-70575-2' },
  { title: 'ELECTRICAL CABLES HANDBOOK', author: 'G. F. MOORE', category: 'ELECTRICITY', isbn: '978-0-632-04075-9' },
  { title: 'ELECTRICAL CABLES HANDBOOK', author: 'G. F. MOORE', category: 'ELECTRICITY', isbn: '978-0-632-04075-9' },
  { title: 'ELECTRICAL INSTALLATION PRACTICE', author: 'GEOFFREY STOKES', category: 'ELECTRICITY', isbn: '978-0-632-06002-3' },
  { title: 'ELECRTICAL AND MECHANICAL ENGINEERING', author: 'ERIC H. GLENDINNING', category: 'ELECTRICITY', isbn: '0-19-457392-3' },
  { title: 'ELECTRICAL AND MECHANICAL ENGINEERING', author: 'ERIC H. GLENDINNING', category: 'ELECTRICITY', isbn: 'ELT ELECTRICAL & MECHANICAL 001' },
  { title: 'ELECTRICAL AND MECHANICAL ENGINEERING', author: 'ERIC H. GLENDINNING', category: 'ELECTRICITY', isbn: 'ELT ELECTRICAL & MECHANICAL 002' },
  { title: 'VH BASICS', author: 'NONE', category: 'ELECTRICITY', isbn: 'ELT VHS BASICS 001' },
  { title: 'WHEELS AND CASTORS', author: 'NONE', category: 'ELECTRICITY', isbn: 'ELT WHEELS & CASTORS' },
  { title: 'FUNDAMENTALS OF ELECTRIC CIRCUITS', author: 'CHALRES K. ALEXANDER', category: 'ELECTRICITY', isbn: '978-1-259-25132-0' },
  { title: 'CROSSROAD PUZZLERS', author: 'DAVID WEBSTER', category: 'ELECTRICITY', isbn: 'ELT CROSSROAD 001' },
  { title: 'AUTOMOTIVE BEARING LIST 1985', author: 'ELANDERS', category: 'ELECTRICITY', isbn: 'ELT AUTO-BEARING 001' },
  { title: 'DATA ACQUISITION DATABOOK UPDATE AND SELECTION GUIDE', author: 'NONE', category: 'ELECTRICITY', isbn: 'ELT DATA ACQUISITION 001' },
  { title: 'C++', author: 'ROB MC GREGOR', category: 'PROGRAMMING', isbn: 'ETE C++ 001' },
  { title: 'C++', author: 'ROB MC GREGOR', category: 'PROGRAMMING', isbn: 'ETE C++ 002' },
  { title: 'C++', author: 'ROB MC GREGOR', category: 'PROGRAMMING', isbn: 'ETE C++ 003' },
  { title: 'C++', author: 'ROB MC GREGOR', category: 'PROGRAMMING', isbn: 'ETE C++ 004' },
  { title: 'C++', author: 'ROB MC GREGOR', category: 'PROGRAMMING', isbn: 'ETE C++ 005' },
  { title: 'C PROGRAMMING', author: 'KLAUS SCHRODER', category: 'PROGRAMMING', isbn: 'ETE C PROGRAMMING 001' },
  { title: 'C PROGRAMMING', author: 'KLAUS SCHRODER', category: 'PROGRAMMING', isbn: 'ETE C PROGRAMMING 002' },
  { title: 'C PROGRAMMING', author: 'KLAUS SCHRODER', category: 'PROGRAMMING', isbn: 'ETE C PROGRAMMING 003' },
  { title: 'C PROGRAMMING', author: 'KLAUS SCHRODER', category: 'PROGRAMMING', isbn: 'ETE C PROGRAMMING 004' },
  { title: 'C PROGRAMMING', author: 'KLAUS SCHRODER', category: 'PROGRAMMING', isbn: 'ETE C PROGRAMMING 005' },
  { title: 'EEPT', author: 'JOHN BIRD', category: 'ELECTRONICS', isbn: 'ETE EEPT 001' },
  { title: 'EEPT', author: 'JOHN BIRD', category: 'ELECTRONICS', isbn: 'ETE EEPT 002' },
  { title: 'EEPT', author: 'JOHN BIRD', category: 'ELECTRONICS', isbn: 'ETE EEPT 003' },
  { title: 'EEPT', author: 'JOHN BIRD', category: 'ELECTRONICS', isbn: 'ETE EEPT 004' },
  { title: 'EEPT', author: 'JOHN BIRD', category: 'ELECTRONICS', isbn: 'ETE EEPT 005' },
  { title: 'EEPT', author: 'JOHN BIRD', category: 'ELECTRONICS', isbn: 'ETE EEPT 006' },
  { title: 'EMERGING MULTIMEDIA COMPUTER COMMUNICATION', author: 'J. DAVID IRWIN', category: 'TELOCOMMUNICATION', isbn: '0-13-079967-X' },
  { title: 'BASIC ELECTRICAL AND ELECTRONIC ENGINEERING PRINCIPLES', author: 'R J MADDOCK', category: 'ELECTRONICS', isbn: 'ETE ELECTRONICS 001' },
  { title: 'BASIC ELECTRICAL AND ELECTRONIC ENGINEERING PRINCIPLES', author: 'R J MADDOCK', category: 'ELECTRONICS', isbn: 'ETE ELECTRONICS 002' },
  { title: 'BASIC ELECTRICAL AND ELECTRONIC ENGINEERING PRINCIPLES', author: 'R J MADDOCK', category: 'ELECTRONICS', isbn: 'ETE ELECTRONICS 003' },
  { title: 'BASIC ELECTRICAL AND ELECTRONIC ENGINEERING PRINCIPLES', author: 'R J MADDOCK', category: 'ELECTRONICS', isbn: 'ETE ELECTRONICS 004' },
  { title: 'BASIC ELECTRICAL AND ELECTRONIC ENGINEERING PRINCIPLES', author: 'R J MADDOCK', category: 'ELECTRONICS', isbn: 'ETE ELECTRONICS 005' },
  { title: 'BASIC ELECTRICAL AND ELECTRONIC ENGINEERING PRINCIPLES', author: 'R J MADDOCK', category: 'ELECTRONICS', isbn: 'ETE ELECTRONICS 006' },
  { title: 'BASIC ELECTRICAL AND ELECTRONIC ENGINEERING PRINCIPLES', author: 'R J MADDOCK', category: 'ELECTRONICS', isbn: 'ETE ELECTRONICS 007' },
  { title: 'COMPUTER NETWORKING', author: 'NONE', category: 'NETWORKING', isbn: 'ETE NETWORKING 001' },
  { title: 'COMUTER NETWORKING', author: 'NONE', category: 'NETWORKING', isbn: 'ETE NETWORKING 002' },
  { title: 'COMPUTER NETWORKING', author: 'NONE', category: 'NETWORKING', isbn: 'ETE NETWORKING 003' },
  { title: 'COMPUTER NETWORKING', author: 'NONE', category: 'NETWORKING', isbn: 'ETE NETWORKING 004' },
  { title: 'COMPUTER NETWORKING', author: 'NONE', category: 'NETWORKING', isbn: 'ETE NETWORKING 005' },
  { title: 'DIGITAL ELECTRONICS', author: 'BRYON W. PUTMAN', category: 'ELECTRONICS', isbn: 'ETE DIGITAL 001' },
  { title: 'DIGITAL ELECTRONICS', author: 'BRYON W. PUTMAN', category: 'ELECTRONICS', isbn: 'ETE DIGITAL 002' },
  { title: 'BASIC ELECTRONICS AND LINEAR CIRCUITS', author: 'N N BHARGAVA', category: 'ELECTRONICS', isbn: 'ETE BASIC ELECTRONICS 001' },
  { title: 'BASIC ELECTRONICS AND LINEAR CIRCUITS', author: 'N N BHARGAVA', category: 'ELECTRONICS', isbn: 'ETE BASIC ELECTRONICS 002' },
  { title: 'DATA AND COMPUTER COMMUNICATIONS', author: 'WILLIAM STALLINGS', category: 'NETWORKING', isbn: '1-129-01438-5' },
  { title: 'ELECTRONICS', author: 'REX MILLER', category: 'ELECTRONICS', isbn: '0-8120-9144-2' },
  { title: 'DATA HANDBOOK', author: 'PHILIPS', category: 'ELECTRONICS', isbn: 'ETE DATA HANDBOOK 001' },
  { title: 'SYBA LAB', author: 'NONE', category: 'ELECTRONICS', isbn: 'ETE SYSBALAB 001' },
  { title: 'DATA CONVERTERS AND VOLTAGE REFERENCES', author: 'NONE', category: 'ELECTRONICS', isbn: 'ETE DATA CONVERTER 001' },
  { title: 'FLUENCY WITH INFORMATION TECHNOLOGY', author: 'LAWRENCE SYNYDER', category: 'ELECTRONICS', isbn: '978-1-256-80453-6' },
  { title: 'MICRO COMPUTER ENGINEERING-MODULAR', author: 'NONE', category: 'ELECTRONICS', isbn: 'ETE MICROCOMP ENG 001' },
  { title: 'DOT MATRIX', author: 'NONE', category: 'ELECTRONICS', isbn: 'ETE DOT MATRIX 001' },
  { title: 'DOT MATRIX', author: 'NONE', category: 'ELECTRONICS', isbn: 'ETE DOT MATRIX 002' },
  { title: 'TRAINING SYSTEM FOR AUTOMATION TECHNOLOGY', author: 'NONE', category: 'ELECTRONICS', isbn: 'ETE AUTOMATION 001' },
  { title: 'ELECTRONIC DEVICES AND CIRCUIT TECHNOLOGY', author: 'ROBERT BOYLESTAD', category: 'ELECTRONICS', isbn: 'ETE DEVICES CIRCUIT 001' },
  { title: 'MOS POWER DATA BOOK', author: 'NONE', category: 'ELECTRONICS', isbn: 'ETE MOS POWER 001' },
  { title: 'INTRODUCTORY RADIO AND TELEVISION ELECTRONICS', author: 'J.J.JOHNSON', category: 'ELECTRONICS', isbn: '0-333-61656-1' },
  { title: 'SEMI CONDUCTOR AND INTEGRATED CIRCUITS', author: 'NONE', category: 'ELECTRONICS', isbn: 'ETE SEMI CONDUCTOR 001' },
  { title: 'SEMI CONDUCTOR AND INTEGRATED CIRCUITS', author: 'NONE', category: 'ELECTRONICS', isbn: 'ETE SEMIN CONDUCTOR 002' },
  { title: 'ELECTRON TUBE', author: 'NONE', category: 'ELECTRONICS', isbn: 'ETE ELECTRON TUBE 001' },
  { title: 'VHF AND UHF MANUAL', author: 'G.RJESSOP', category: 'ELECTRONICS', isbn: '0-900612-92-4' },
  { title: 'INTEGRATED CIRCUITS', author: 'NONE', category: 'ELECTRONICS', isbn: 'ETE INTEGRATED CIRCUIT 001' },
  { title: 'ELECTRONICS FOR ENGINEERS', author: 'R.J.MADDOCK', category: 'ELECTRONICS', isbn: '0-582-21583-8' },
  { title: 'wood workers manual', author: 'Albert Jackson', category: 'hand tools', isbn: 'wood workers 003' },
  { title: 'wood workers manual', author: 'Albert Jackson', category: 'hand tools', isbn: 'wood workers 002' },
  { title: 'wood workers manual', author: 'Albert Jackson', category: 'hand tools', isbn: 'wood workers 001' },
  { title: 'wood worker manual', author: 'Albert Jackson', category: 'hand tools', isbn: 'wood workers 004' },
  { title: 'wood occupation', author: 'peter brett', category: 'hand tools', isbn: 'wot wood occupation 001' },
  { title: 'wood occupation', author: 'peter brett', category: 'hand tools', isbn: 'wot wood occupation 002' },
  { title: 'carpentry fundamentals', author: 'Don Whyte', category: 'joint construction', isbn: 'Wot carpentry 001' },
  { title: 'carpentry fundamentals', author: 'Don Whyte', category: 'joint construction', isbn: 'Wot carpentry 002' },
  { title: 'carpentry fundamentals', author: 'Don Whyte', category: 'joint construction', isbn: 'Wot carpentry 003' },
  { title: 'carpentry fundamentals', author: 'Don Whyte', category: 'joint construction', isbn: 'Wot carpentry 004' },
  { title: 'carpentry fundamentals', author: 'Don Whyte', category: 'joint construction', isbn: 'Wot carpentry 005' },
  { title: 'carpentry fundamentals', author: 'Don Whyte', category: 'joint construction', isbn: 'Wot carpentry 006' },
  { title: 'Tage Frid Teaches wood working', author: 'Sos Hermann Gmeiner', category: 'Joinery', isbn: 'wot wood working 001' },
  { title: 'tage Frid Teaches Wood Working', author: 'Sos Hermann Gmeiner', category: 'Joinery', isbn: 'wot wood working 002' },
  { title: 'Tage Frid teaches wood working', author: 'Sos Hermann Gmeiner', category: 'Joinery', isbn: 'wot wood working 003' },
  { title: 'AUTOCAD', author: 'NONE', category: 'autocad', isbn: 'WOT Auto 001' },
  { title: 'AUTOCAD', author: 'NONE', category: 'autocad', isbn: 'WOT Auto 002' },
  { title: 'AUTOCAD', author: 'NONE', category: 'autocad', isbn: 'WOT Auto 002' },
  { title: 'CARPENTRY AND JOINERY BOOK 1', author: 'David R. Bates', category: 'Joinery', isbn: 'wot  Joinery oo1' },
  { title: 'carpentry and joinery', author: 'David R. Bates', category: 'Joinery', isbn: 'wot  Joinery oo2' },
  { title: 'carpentry and Joinery bbok 1', author: 'David R. Bates', category: 'Joinery', isbn: 'wot  Joinery oo3' },
  { title: 'carpentry and joinery book1', author: 'David R. Bates', category: 'Joinery', isbn: 'wot  Joinery oo4' },
  { title: 'Tage Frid teaches wood working', author: 'Sos Hermann Gmeiner', category: 'Joinery', isbn: 'wot  Joinery oo4' },
  { title: 'carpentry and joinery book1', author: 'David R. Bates', category: 'Joinery', isbn: '0-582-99479-9' },
  { title: 'Illustrated cabinet making', author: 'Sos Hermann Gmeiner', category: 'Joinery', isbn: 'wot cabinet making oo1' },
  { title: 'Illustrated cabinet making', author: 'Sos Hermann Gmeiner', category: 'Joinery', isbn: 'wot cabinet making oo2' },
  { title: 'Illustrated cabinet making', author: 'Sos Hermann Gmeiner', category: 'Joinery', isbn: 'wot cabinet making oo3' },
  { title: 'Illustrated cabinet making', author: 'Sos Hermann Gmeiner', category: 'Joinery', isbn: 'wot cabinet making oo4' },
  { title: 'Illustrated cabinet making', author: 'Sos Hermann Gmeiner', category: 'Joinery', isbn: 'wot cabinet making oo4' },
  { title: 'Illustrated cabinet making', author: 'Sos Hermann Gmeiner', category: 'Joinery', isbn: 'wot cabinet making oo5' },
  { title: 'Illustrated cabinet making', author: 'Sos Hermann Gmeiner', category: 'Joinery', isbn: 'wot cabinet making oo6' },
  { title: 'MOTIVATE WOOD WORK TECHNOLOGY', author: 'J.K.N  Sackey', category: 'hand tools', isbn: 'Wot Motivate 001' },
  { title: 'MOTIVATE WOOD WORK TECHNOLOGY', author: 'J.K.N  Sackey', category: 'hand tools', isbn: '0-333-60053-3' },
  { title: 'ENGINEERING DRAWING', author: 'EUGENE G. PARE', category: 'drawing', isbn: 'wot drawing oo1' },
  { title: 'workshop processes, practice and materials 2nd edition 001', author: 'BRUCE J BLACK', category: 'PRACTICE', isbn: '0-340-69252-9' },
  { title: 'WORKSHOP PROCESSES, PRACTICE AND MATERIALS 2ND EDITION 002', author: 'BRUCE J BLACK', category: 'PRACTICE', isbn: '0-340-69252-9' },
  { title: 'Intoducing wood& metal', author: 'Jahn Parry and Warren Frost', category: 'practice', isbn: '0-333-44127-3' },
  { title: 'basic welding OO1', author: 'P.SOMSKY', category: 'WELDING', isbn: '0-333-42610-X' },
  { title: 'Basic of welding 002', author: 'P. SOMSKY', category: 'WELDING', isbn: '0-333-42610-X' },
  { title: 'MODERN PLUMBING', author: 'E.KEITH BLANKENBAKER', category: 'PLUMBING', isbn: 'PWO M-PLUMBING 001' },
  { title: 'MODERN PLUMBING', author: 'E.KEITH BLANKENBAKER', category: 'PLUMBING', isbn: 'PWO M-PLUMBING 002' },
  { title: 'PLUMBING', author: 'E.KEITH BLANKENBAKER', category: 'PLUMBING', isbn: 'PWO PLUMBING 001' },
  { title: 'PLUMBING', author: 'E.KEITH BLANKENBAKER', category: 'PLUMBING', isbn: 'PWO PLUMBING 002' },
  { title: 'PLUMBING', author: 'E.KEITH BLANKENBAKER', category: 'PLUMBING', isbn: 'PWO PLUMBING 003' },
  { title: 'PLUMBING STUDIES', author: 'STEPHEN BLAIR', category: 'PLUMBING', isbn: '978-1-4479-4023-4' },
  { title: 'ENGINEERING DRAWING AND GRAPHIC TECHNOLOGY', author: 'THOMAS E.FRENCH', category: 'DRAWING', isbn: '0-07-113302-X' },
  { title: 'SMALL-SCALE WATER SUPPLY', author: 'BRIAAN SKINNER', category: 'WATER SUPLLY', isbn: 'PWO SSWS 001' },
  { title: 'FARM WATER SUPPLIES DESIGN MANUAL VOL1', author: 'A.J. HORTON', category: 'WATER SUPLLY', isbn: 'PWO FWSDM 002' },
  { title: 'SMALL-SCALE WATER SUPPLY', author: 'BRIAAN SKINNER', category: 'WATER SUPLLY', isbn: 'PWO SSWS 001' },
  { title: 'THE MOTIVATE METAL WORK TECHNOLOGY', author: 'J.K.N.SACKEY', category: 'METAL WORK', isbn: 'PWO MOT METALWORK TECH 002' },
  { title: 'THE MOTIVATE', author: 'J.K.N.Sackey', category: 'METAL WORK', isbn: 'pwo mot Metal work tech 001' },
  { title: 'HIGHWAY ENGINERRING', author: 'NONE', category: 'ENGINEERING', isbn: 'PWO HE 001' },
  { title: 'WATER_RESOURCES ENGINNERING', author: 'DAVID A.CHIN', category: 'WATER SUPPLY', isbn: 'PWO WRE 001' },
  { title: 'WATER-RESOURCES ENGINEERING', author: 'DAVID A. CHIN', category: 'WATER SUPLLY', isbn: 'PWO WRE 002' },
  { title: 'DISK BASIC', author: 'NONE', category: 'DISK', isbn: 'PWO DB 001' },
  { title: 'WATER SUPPLY AND WASTEWATER ENGINNERING', author: 'B S N RAJU', category: 'WATER SUPPLY', isbn: 'PWO WSWW 001' },
  { title: 'FARM WATER SUPPLIES DESIGN MANUAL VOL3', author: 'A.J. HORTON', category: 'WATER SUPLLY', isbn: 'PWO FWSDM 001' },
  { title: 'MODERN METAL WORKING', author: 'JOHN R. WALKER', category: 'METAL WORK', isbn: 'PWO M_METAL WORKING 001' },
  { title: 'HIGHWAY MATERIALS AND PAVEMENT TESTING', author: 'S.K. KHANA', category: 'PAVEMENT', isbn: 'LSU HMPT 001' },
  { title: 'HIGHWAY MATERIALS AND PAVEMENT TESTING', author: 'S.K.KHANNA', category: 'PAVEMENT', isbn: 'LSV HMTP 002' },
  { title: 'HIGHWAY MATERIALS AND PAVEMENT TESTING', author: 'S.K. KHANA', category: 'PAVEMENT', isbn: 'LSU HMPT 003' },
  { title: 'HIGHWAY MATERIALS AND PAVEMENT TESTING', author: 'S.K. KHANA', category: 'PAVEMENT', isbn: 'LSU HMPT 004' },
  { title: 'HIGHWAY MATERIALS AND PAVEMENT TESTING', author: 'S.K. KHANA', category: 'PAVEMENT', isbn: 'LSU HMPT 004' },
  { title: 'HIGHWAY MATERIALS AND PAVEMENT TESTING', author: 'S.K. KHANA', category: 'PAVEMENT', isbn: 'LSU HMPT 004' },
  { title: 'HIGHWAY MATERIALS AND PAVEMENT TESTING', author: 'S.K.KHANNA', category: 'PAVEMENT', isbn: 'LSV HMPT 005' },
  { title: 'HIGHWAY MATERIALS AND PAVEMENT TESTING', author: 'S.K. KHANA', category: 'PAVEMENT', isbn: 'LSU HMPT 004' },
  { title: 'SURVEYING(VOLUME 2)', author: 'Dr.B.C. PUNMIA', category: 'SURVEYING', isbn: 'LSV SURVEYING II 001' },
  { title: 'HIGHWAY MATERIALS AND PAVEMENT TESTING', author: 'S.K. KHANA', category: 'PAVEMENT', isbn: 'LSU HMPT 004' },
  { title: 'GPS SATELLITE SURVEYING', author: 'ALFRED LEICK', category: 'SURVEYING', isbn: '978_1_118_67557-1' },
  { title: 'PLANE SURVEY', author: 'JE JACKSON', category: 'SURVEYING', isbn: '81-239-1172-6' },
  { title: 'SURVEYING', author: 'B.C. PUNMIA', category: 'SURVEYING', isbn: 'LSV SURVEYING 001' },
  { title: 'THE SURVEYING HANDBOOK VOLUME II', author: 'RUSSELL C. BRINKER', category: 'SURVEYING', isbn: '978-1-4613-5858-9' },
  { title: 'SURVEYING', author: 'B.C. PUNMIA', category: 'SURVEYING', isbn: 'LSV SURVEYING 005' },
  { title: 'SURVEYING', author: 'B.C. PUNMIA', category: 'SURVEYING', isbn: 'LSV SURVEYING 004' },
  { title: 'SURVEYING WITH CONSTRUCTION APPLICATIONS', author: 'BARRY F. KAVANAGH', category: 'SURVEYING', isbn: 'LSV SCA 003' },
  { title: 'SURVEYING WITH CONSTRUCTION APPLICATIONS', author: 'BARRY F. KAVANAGH', category: 'SURVEYING', isbn: 'LSV SCA 001' },
  { title: 'SURVEYING WITH CONSTRUCTION APPLICATIONS', author: 'BARRY F. KAVANAGH', category: 'SURVEYING', isbn: 'LSV SCA 002' },
  { title: 'SURVEYING', author: 'B.C. PUNMIA', category: 'SURVEYING', isbn: 'LSV SURVEYING 002' },
  { title: 'SURVEYING', author: 'B.C. PUNMIA', category: 'SURVEYING', isbn: 'LSV SURVEYING 003' },
  { title: 'WATER SUPPLY AND WASTEWATER ENGINERING', author: 'BSN RAJU', category: 'WATER SUPLLY', isbn: 'LSV WSWW 001' },
  { title: 'WATER SUPPLY AND WASTEWATER ENGINERING', author: 'BSN RAJU', category: 'WATER SUPLLY', isbn: 'LSV WSWW 002' },
  { title: 'WATER SUPPLY ENGINERING', author: 'B.C. PUNMIA', category: 'WATER SUPLLY', isbn: 'LSV WSE 001' },
  { title: 'WATER SUPPLY ENGINEERING', author: 'B.C. PUNMIA', category: 'WATER SUPLLY', isbn: 'LSV WSE 002' },
  { title: 'HIGHWAY ENGINNERING', author: 'NONE', category: 'SURVEYING', isbn: 'LSV HE 001' },
  { title: 'WATER SUPPLY ENGINEERING', author: 'B.C. PUNMIA', category: 'WATER SUPLLY', isbn: 'LSV WSE 003' },
  { title: 'PART II CONSTRUCTION APPLICATION', author: 'NONE', category: 'CONSTRUCTION', isbn: 'LSV CA 002' },
  { title: 'SMALL_SCALE WATER SUPPLY', author: 'BRIAN SKINNER', category: 'SURVEYING', isbn: 'LSV SSWS 001' },
  { title: 'PART II CONSTRUCTION APPLICATION', author: 'NONE', category: 'CONSTRUCTION', isbn: 'LSV CA 001' },
  { title: 'ROAD CONSTRUCTION MATERIALS', author: 'J. KISUNGE', category: 'CONSTRUCTION', isbn: 'LSV RCM 001' },
  { title: 'SMALL_SCALE WATER SUPPLY', author: 'BRIAN SKINNER', category: 'SURVEYING', isbn: 'LSVSSWS 002' },
  { title: 'QUALITY SURVEYING', author: 'NONE', category: 'SURVEYING', isbn: 'LSV QS 001' },
  { title: 'ENGINEERING DRAWING PROBLEMS', author: 'E.V. MOCHEL', category: 'DRAWING', isbn: 'LSV EDP 001' },
  { title: 'FARM WATER SUPPLIES VOL III', author: 'A.J. HORTON', category: 'WATER SUPLLY', isbn: 'LSV WSDM 004' },
  { title: 'FARM WATER SUPPLIES VOL III', author: 'A.J. HORTON', category: 'WATER SUPLLY', isbn: 'LSV WSDM 005' },
  { title: 'FARM WATER SUPPLIES VOL I', author: 'A.J. HORTON', category: 'WATER SUPLLY', isbn: 'LSV WSDM 001' },
  { title: 'FARM WATER SUPPLIES DESIGN MANUAL VOL II', author: 'A.J. HORTON', category: 'WATER SUPLLY', isbn: 'LSV FWSDM 001' },
  { title: 'DICTIONARY OF BUILDING AND CIVIL ENGINEERING', author: 'DON MONTAGUE', category: 'CONSTRUCTION', isbn: 'BDC DBCE 001' },
  { title: 'FARM WATER SUPPLIES VOL II', author: 'A.J. HORTON', category: 'WATER SUPLLY', isbn: 'LSV FWSDM 006' },
  { title: 'FARM WATER SUPPLIES VOL II', author: 'A.J. HORTON', category: 'WATER SUPLLY', isbn: 'LSV FWSDM 003' },
  { title: 'DICTIONARY OF BUILDING AND CIVIL ENGINEERING', author: 'DON MONTAGUE', category: 'CONSTRUCTION', isbn: 'BDC ABCE 002' },
  { title: 'RURAL BUILDING COURSE VOL2', author: 'BRO. JOHN V. WINDEN', category: 'CONSTRUCTION', isbn: 'BDC RBC 002' },
  { title: 'RURAL BUILDING COURSE VOL4', author: 'BRO. JOHN V. WINDEN', category: 'CONSTRUCTION', isbn: 'BDC RBC 001' },
  { title: 'RURAL BUILDING(VOLUME 1)', author: 'NONE', category: 'CONSTRUCTION', isbn: 'BDC RB 001' },
  { title: 'RURAL BUILDING VOL3', author: 'BRO. JOHN V. WINDEN', category: 'CONSTRUCTION', isbn: 'BDC RB 002' },
  { title: 'CONCRETE FORMWORK', author: 'LEONARD COEL', category: 'CONSTRUCTION', isbn: '978_0_8269_0710_3' },
  { title: 'ENGINEERING DRAWING AND GRAPHIC TECHNOLOGY', author: 'THOMAS E.FRENCH', category: 'DRAWING', isbn: 'BDC EDGT 003' },
  { title: 'ENGINEERING DRAWING AND GRAPHIC TECHNOLOGY', author: 'THOMAS E.FRENCH', category: 'DRAWING', isbn: 'BDC EDGT 001' },
  { title: 'BASIC CONSTRUCTION MATERIALS', author: 'THEODORE W.MAROTTA', category: 'CONSTURUCTION', isbn: '0_13_089625_X' },
  { title: 'BRICK WORK', author: 'HEINEMANN', category: 'BRICK', isbn: '978-0-435027-07-0' },
  { title: 'PLUMBING MECHANICAL SERVICES', author: 'G.J.BLOWER', category: 'CONSTRUCTION', isbn: '0_13_197620-B' },
  { title: 'BUILDING TECHNOLOGY', author: 'IVOR H. SEELEY', category: 'CONSTRUCTION', isbn: 'BDC BT 001' },
  { title: 'BRICK WORK', author: 'HEINEMANN', category: 'BRICK', isbn: '978-0-435027-07-0' },
  { title: 'CONCRETE FORMWORK', author: 'LEONARD COEL', category: 'CONSTRACTION', isbn: '978_0_8269_0773_8' },
  { title: 'MODERN MASONRY', author: 'CLOIS E. KICKLIGHTER', category: 'CONSTRUCTION', isbn: '978-1-60525-243-8' },
  { title: 'WATER SUPPLY AND WASTEWATER ENGINEERING', author: 'BSN RAJU', category: 'WATER SUPLLY', isbn: 'BDC WSSE 001' },
  { title: 'CONSTRUCTION', author: 'SIMON TOPLISS', category: 'CONSTRUCTION', isbn: '978_1_84690_935-1' },
  { title: 'BUILDING CONSTRUCTION', author: 'DR. B.C. PUNMIA', category: 'CONSTRUCTION', isbn: 'BDC BC 002' },
  { title: 'HEALTH SAFETY CONSTRUCTION', author: 'PHIL HUGHES', category: 'CONSTRUCTION', isbn: '978-0-08-097068-4' },
  { title: 'THE MOTIVATE', author: 'D.WALTON', category: 'CONSTRUCTION', isbn: 'BDC MOT BCPP 001' },
  { title: 'BUILDING A HOUSE FRAMING PRACTICES', author: 'CHARLES SIMPSON', category: 'CONSTRUCTION', isbn: 'BDC BHFP 001' },
  { title: 'BUILDING A HOUSE FRAMING PRACTICES', author: 'CHARLES SIMPSON', category: 'CONSTRUCTION', isbn: 'BDC BHFP 002' },
  { title: 'THE MOTIVATE', author: 'A.YARWOOD', category: 'CONSTRUCTION', isbn: 'BDC MOT TDDS 001' },
  { title: 'PART II CONSTRUCTION APPLICATION', author: 'NONE', category: 'CONSTRUCTION', isbn: 'BDC CA 001' },
  { title: 'BUILDING CONSTRUCTION', author: 'DR. B.C. PUNMIA', category: 'CONSTRUCTION', isbn: 'BDC BC003' },
  { title: 'BUILDING CONSTRUCTION', author: 'DR. B.C. PUNMIA', category: 'CONSTRUCTION', isbn: 'BDC BC 004' },
  { title: 'MODERN MASONRY', author: 'Clois E.KICKLIGHTER', category: 'CONSTRUCTION', isbn: 'BDC M_MASONRY 003' },
  { title: 'MASONRY', author: 'HENRY R. LUCE', category: 'CONSTRUCTION', isbn: 'BDC MASONARY 001' },
  { title: 'CONSTRUCTION DRAWING PRACTICES', author: 'NONE', category: 'CONSTRUCTION', isbn: 'BDC CDP 001' },
  { title: 'MODERN MASONRY', author: 'Clois E.KICKLIGHTER', category: 'CONSTRUCTION', isbn: 'BDC M-MASONARY 001' },
  { title: 'CONSTRUCTION DRAWING PRACTICES', author: 'NONE', category: 'CONSTRUCTION', isbn: 'BDC CDP 002' },
  { title: 'CONSTRUCTION DRAWING PRACTICES', author: 'NONE', category: 'CONSTRUCTION', isbn: 'BDC CDP 003' },
  { title: 'BUILDING CONSTRUCTION', author: 'DR. B.C. PUNMIA', category: 'CONSTRUCTION', isbn: 'BDC BC 005' },
  { title: 'BUILDING CONSTRUCTION', author: 'DR. B.C. PUNMIA', category: 'CONSTRUCTION', isbn: 'BDC BC 006' },
  { title: 'MODERN MASONRY', author: 'Clois E.KICKLIGHTER', category: 'CONSTRUCTION', isbn: 'BDC M_MASONARY 002' },
  { title: 'STRENGTH OF MATRIALS INTRODUCTION PRINCIPLES', author: 'KWESI ANDAM', category: 'CONSTRUCTION', isbn: 'BDC SMIPA 001' },
  { title: 'RURAL BUILDING(VOLUME 1)', author: 'NONE', category: 'CONSTRUCTION', isbn: 'BDC RB 003' },
  { title: 'INTRODUCTION TO ENGINEERING TECHNOLOGY', author: 'ROBERT J. POND', category: 'ENGINEERING', isbn: 'BDC IET 001' },
  { title: 'TECHNICAL DRAWING FOR SCHOOOLS AND COLLEGES', author: 'B.J.OKELO AMBOK', category: 'DRAWING', isbn: 'BDC TDSC 003' },
  { title: 'TECHNICAL DRAWING FOR SCHOOOLS AND COLLEGES', author: 'B.J.OKELO AMBOK', category: 'DRAWING', isbn: 'BDC TDSC 004' },
  { title: 'CONSTRUCTION COMPETENCE FOR NVQ LEVER 2', author: 'W.G. NASH', category: 'CONSTRUCTION', isbn: 'BDC CC 001' },
  { title: 'BRICK WORK', author: 'HEINEMANN', category: 'BRICK', isbn: 'BDC BW 001' },
  { title: 'OWNER BUILDERS MANUAL', author: 'ALLAN STAINES', category: 'CONSTRUCTION', isbn: 'BDC OBM 001' },
  { title: 'CIVIL ENGINEERING MATERIALS', author: 'SHAN SOMAYAJI', category: 'CONSTRUCION', isbn: 'BDC CEM 002' },
  { title: 'CIVIL ENGINEERING MATERIAL', author: 'SHAN SOMAYAJI', category: 'CONSTRUCTION', isbn: 'BDC CEM 002' },
  { title: 'CONSTRUCTION DRAWING PRACTICES', author: 'NONE', category: 'DRAWING', isbn: 'BDC CDP 004' },
  { title: 'ENGINEERING DRAWING', author: 'E.M.OWOEYE', category: 'CONSTRUCTION', isbn: 'BDC ED 001' },
  { title: 'MASONRY', author: 'HENRY', category: 'CONSTRUCTION', isbn: 'BDC MASONARY 002' },
  { title: 'CONSTRUCTION TECHNOLOGY EDITION2', author: 'MARLK W. HUTH', category: 'CONSTRUCTION', isbn: 'BDC CT 004' },
  { title: 'CONSTRUCTION TECHNOLOGY', author: 'R.CHUDLEY', category: 'CONSTRUCTION', isbn: 'BDC CT 003' },
  { title: 'CIVIL ESTIMATING,CONSTRUCTION AND VALUATION', author: 'AMRJIC AGGARWAL', category: 'CONSTRUCTION', isbn: 'BDC CECV 004' },
  { title: 'CIVIL ESTIMATING,CONSTRUCTION AND VALUATION', author: 'AMRJIC AGGARWAL', category: 'CONSTRUCTION', isbn: 'BDC CECV 003' },
  { title: 'CIVIL ESTIMATING,CONSTRUCTION AND VALUATION', author: 'AMRJIC AGGARWAL', category: 'CONSTRUCTION', isbn: 'BDC CECV 001' },
  { title: 'THE AUSTRALIAN OWNER BUILDING MANUAL', author: 'ALLAN STAINES', category: 'CONSTRUCTION', isbn: 'BDC OBM 002' },
  { title: 'CIVIL ESTIMATING,CONSTRUCTION AND VALUATION', author: 'AMRJIC AGGARWAL', category: 'CONSTRUCTION', isbn: 'BDC CECV 002' },
  { title: 'BUILDING AND CIVIL ENGINEERING', author: 'DON MONTAGE', category: 'ENGINEERING', isbn: 'BDC DBCE 003' },
  { title: 'CONSTRUCTION TECHNOLOGY', author: 'R. CHUDLEY', category: 'CONSTRUCTION', isbn: 'BDC CT 005' },
  { title: 'THE MOTIVATE', author: 'A. YARWOOD', category: 'CONSTRUCTION', isbn: 'BDC MOT TDD 002' },
  { title: 'STRENGTH OF MATERIALS', author: 'KWESI ANDAM', category: 'CONSTRUCTION', isbn: 'BDC SMIPA 002' },
  { title: 'BUILDING A HOUSE FRAMING PRACTICES', author: 'CHARLES SIMPSON', category: 'CONSTRUCTION', isbn: 'BDC BHFP 003' },
  { title: 'CONCRETE TECHNOLOGY', author: 'A.M. NEVILLE', category: 'CONSTRUCTION', isbn: 'BDC CT 001' },
  { title: 'THE AUSTRALIAN BUILDERS MANUAL', author: 'ALLAN STAINES', category: 'CONSTRUCTION', isbn: 'BDC OBM 003' },
  { title: 'CONCRETE TECHNOLOGY', author: 'A.M. NEVILLE', category: 'CONSTRUCTION', isbn: 'BDC CT 002' },
  { title: 'BUILDING CONTRUCTION', author: 'DR. B.C. PUNMIA', category: 'CONSTRUCTION', isbn: 'BDC BC 007' },
  { title: 'TEXT BOOK OF BUILDING CONSTRUCTION', author: 'Dr.B.C. PUNMIA', category: 'CONSTRUCTION', isbn: 'BDC BC 003' },
  { title: 'TECHNICAL DRAWING FOR SCHOOLS AND COLLEGES', author: 'B.J.OKELO AMBOK', category: 'DRAWING', isbn: 'BDC TDSC 005' },
  { title: 'WATER SUPPLY AND WASTEWATER ENGINEERING', author: 'B S N RAJU', category: 'WATER SUPPLY', isbn: 'BDC WSWWE 001' },
  { title: 'BUILDING CONSTRUCTION HANDBOOK', author: 'R. CHUDLEY', category: 'CONSTRUCTION', isbn: 'BDC BCH 001' },
  { title: 'WATER SUPPLY ENGINEERING', author: 'B.C. PUNMIA', category: 'WATER SUPLLY', isbn: 'BDC WSE 001' },
  { title: 'TECHNICAL DRAWING WITH DESIGN', author: 'A. YARWOOD', category: 'CONSTRUCION', isbn: 'BDC MOT TDD 001' },
  { title: 'BUILDING CONSTRUCTION PRINCIPLES AND PRACTICES', author: 'D. WALTSON', category: 'CONSTRUCTION', isbn: 'BDC MAT BCPP 002' },
  { title: 'CONSTRUCTION TECHNOLOGY AND MANAGEMENT', author: 'ROBERT NEWCOMBE', category: 'CONSTRUCTION', isbn: 'BDC CTM 002' },
  { title: 'CONSTRUCTION TECHNOLOGY AND MANAGEMENT', author: 'ROBERT NEWCOMBE', category: 'CONSTRUCTION', isbn: 'BDC CTM 001' },
  { title: 'CONSTRUCTION TECHNOLGY AND MANAGEMENT', author: 'ROBERT NEWCOMBE', category: 'CONSTRUCTION', isbn: 'BDC CTM 003' },
  { title: 'BUILDING CONSTRUCTION', author: 'DR. B.C. PUNMIA', category: 'CONSTRUCTION', isbn: 'BDC BC 001' },
  { title: 'BUILDING CONSTRUCTION HANDBOOK', author: 'ROY CHUDLEY', category: 'CONSTRUCTION', isbn: '978_1-138_90709_6' },
  { title: 'MODERN MASONRY', author: 'CLOIS E. KICKLIGHTER', category: 'CONSTRUCTION', isbn: 'BDC M-MASONARY 004' },
  { title: 'CIVIL ENGINEERING MATERIAL', author: 'CLOIS E. KICKLIGHTER', category: 'CONSTRUCTION', isbn: 'BDC CEM 003' },
  { title: 'CONSTRUCTION TECHNOLOGY', author: 'ROY CHUDLEY', category: 'CONSTRUCTION', isbn: 'BDC CT 004' },
  { title: 'MODERN MASONRY', author: 'CLOIS E. KICKLIGHTER', category: 'CONSTRUCTION', isbn: 'BDC M-MASONARY 003' },
  { title: 'BUILDING CONSTRUCTION : PRINCIPLES AND PRACTICES', author: 'DENIS WALTON', category: 'CONSTRUCTION', isbn: 'BDC BC 009' },
  { title: 'BUILDING TECHNOLOGY', author: 'IVOR H.Seeley', category: 'CONSTRUCTION', isbn: 'BDC BT 002' },
  { title: 'BUILDING CONSTRUCTION HANBOOK', author: 'R. CHUDREY', category: 'CONSTRUCTION', isbn: '0_7506_4649_7' },
  { title: 'BUILDING CONSTRUCTION HANBOOK', author: 'R. CHUDREY', category: 'CONSTRUCTION', isbn: '0_7506_4649_7' },
  { title: 'BRICK WORK', author: 'HEINEMANN', category: 'CONSTRUCTION', isbn: 'BDC BW 002' },
  { title: 'BRICK WORK', author: 'HEINEMANN', category: 'CONSTRUCTION', isbn: 'BDC BW 002' },
  { title: 'BRICK WORK', author: 'HEINEMANN', category: 'CONSTRUCTION', isbn: 'BDC BW 002' },
  { title: 'BRICK WORK', author: 'HEINEMANN', category: 'CONSTRUCTION', isbn: 'BDC BW 002' },
  { title: 'BASIC CONSTRUCTION MATERIALS', author: 'THEODORE W.MAROTTA', category: 'CONSTRUCTION', isbn: '0-13-089625-X' },
  { title: 'CIVIL ENGINEERING MATERIALS', author: 'SHAN SOMAYAJI', category: 'CONSTRUCTION', isbn: '0_13-0839Ob_x' },
  { title: 'PROCUREMENT,TENDERING AND CONTRACT ADMINISTRATION', author: 'MARK HACKETT', category: 'CONSTRUCTION', isbn: '978-1-1183-4654' },
  { title: 'REINFORCED CONCRETE DESIGN', author: 'W.H. MOSLEY', category: 'CONSTRUCTION', isbn: 'BDC RCD 001' },
  { title: 'CONSTRUCTION TECHNOLOGY VOL1', author: 'R. CHUDLEY', category: 'CONSTRUCTION', isbn: 'BDC CT 006' },
  { title: 'BUILDING TECHNOLOGY', author: 'IVOR H.SEELEY', category: 'CONSTRUCTION', isbn: 'BDC BT 003' },
  { title: 'PLASTIC AS DESIGN FORM', author: 'THELMA R. NEWMAN', category: 'CONSTRUCTION', isbn: 'BDC PD 001' },
  { title: 'TECHNICAL DRAWING WITH DESIGN', author: 'A. YARWOOD', category: 'CONSTRUCTION', isbn: 'BDC MOT TDD 003' },
  { title: 'ENGINEERING DRAWING AND GRAPHIC TECHNOLOGY', author: 'THOMAS E.FRENCH', category: 'CONSTRUCTION', isbn: 'BDC EDGT 003' },
  { title: 'ENGINEERING DRAWING AND GRAPHIC TECHNOLOGY', author: 'THOMAS E.FRENCH', category: 'CONSTRUCTION', isbn: 'BDC EDGT 004' },
  { title: 'MASONRY', author: 'None', category: 'CONSTRUCTION', isbn: 'BDC MASONARY 003' },
  { title: 'CONSTRUCTION COMPETENCIES BRICK LAYING', author: 'STANLEY THORNES', category: 'CONSTRUCTION', isbn: 'BDC CC 002' },
  { title: 'BUILDING CONSTRUCTION HANDBOOK', author: 'R.CHUDLEY', category: 'CONSTRUCTION', isbn: 'BDC BCH 002' },
  { title: 'TECHNICAL DRAWING FOR SCHOOLS AND COLLEGES', author: 'B.J.OKELO AMBOK', category: 'DRAWING', isbn: 'BDC TDSC 001' },
  { title: 'TECHNICAL DRAWING FOR SCHOOLS AND COLLEGES', author: 'B.J.OKELO AMBOK', category: 'DRAWING', isbn: 'BDC TDSC 002' },
  { title: 'ENGINEERING DRAWING AND GRAPHIC TECHNOLOGY', author: 'THOMAS E .FRENCH', category: 'CONSTRUCTION', isbn: 'BDC EDGT 002' },
  { title: 'CONSTRUCTION DRAWING PRACTICES', author: 'None', category: 'CONSTRUCTION', isbn: 'BDC CDP 005' },
  { title: 'CONSTRUCTION', author: 'SUE MEREDITH', category: 'CONSTRUCTION', isbn: '978-1-84690-165-2' },
  { title: 'CONSTRUCTION', author: 'SUE MEREDITH', category: 'CONSTRUCTION', isbn: '978-1-84690-165-2' }
];

const allocationsData = [
  { bookId: 3, tableName: 'TABLE 1 SWD' }, { bookId: 4, tableName: 'TABLE 1 SWD' }, { bookId: 5, tableName: 'TABLE 1 SWD' },
  { bookId: 6, tableName: 'table 1 swd' }, { bookId: 7, tableName: 'table 1 swd' }, { bookId: 8, tableName: 'TABLE 1 SWD' },
  { bookId: 9, tableName: 'TABLE 1 SWD' }, { bookId: 10, tableName: 'TABLE 1 SWD' }, { bookId: 11, tableName: 'TABLE 1 SWD' },
  { bookId: 12, tableName: 'TABLE 1 SWD' }, { bookId: 13, tableName: 'TABLE 1 SWD' }, { bookId: 14, tableName: 'TABLE 1 SWD' },
  { bookId: 15, tableName: 'TABLE 1 SWD' }, { bookId: 16, tableName: 'TABLE 1 SWD' }, { bookId: 17, tableName: 'TABLE 1 SWD' },
  { bookId: 18, tableName: 'TABLE 1 SWD' }, { bookId: 19, tableName: 'TABLE 1 SWD' }, { bookId: 24, tableName: 'TABLE 1 SWD' },
  { bookId: 21, tableName: 'TABLE 1 SWD' }, { bookId: 23, tableName: 'TABLE 1 SWD' }, { bookId: 25, tableName: 'TABLE 1 SWD' },
  { bookId: 26, tableName: 'TABLE 1 SWD' }, { bookId: 27, tableName: 'TABLE 1 SWD' }, { bookId: 28, tableName: 'TABLE 1 SWD' },
  { bookId: 29, tableName: 'TABLE 1 SWD' }, { bookId: 30, tableName: 'TABLE 1 SWD' }, { bookId: 31, tableName: 'TABLE 1 SWD' },
  { bookId: 33, tableName: 'TABLE 1 SWD' }, { bookId: 34, tableName: 'TABLE 1 SWD' }, { bookId: 35, tableName: 'TABLE 1 SWD' },
  { bookId: 36, tableName: 'TABLE 1 SWD' }, { bookId: 37, tableName: 'TABLE 1 SWD' }, { bookId: 38, tableName: 'TABLE 1 SWD' },
  { bookId: 39, tableName: 'TABLE 1 SWD' }, { bookId: 40, tableName: 'TABLE 1 SWD' }, { bookId: 41, tableName: 'TABLE 1 SWD' },
  { bookId: 42, tableName: 'TABLE 1 MMP' }, { bookId: 43, tableName: 'TABLE 1 MMP' }, { bookId: 44, tableName: 'TABLE 1 MMP' },
  { bookId: 45, tableName: 'TABLE 1 MMP' }, { bookId: 46, tableName: 'TABLE 1 MMP' }, { bookId: 47, tableName: 'TABLE 1 MMP' },
  { bookId: 48, tableName: 'TABLE 1 MMP' }, { bookId: 49, tableName: 'TABLE 1 MMP' }, { bookId: 50, tableName: 'TABLE 1 MMP' },
  { bookId: 51, tableName: 'TABLE 1 MMP' }, { bookId: 52, tableName: 'TABLE 1 MMP' }, { bookId: 53, tableName: 'TABLE 1 CSA' },
  { bookId: 54, tableName: 'TABLE 1 CSA' }, { bookId: 55, tableName: 'TABLE 1 CSA' }, { bookId: 56, tableName: 'TABLE 1 CSA' },
  { bookId: 57, tableName: 'TABLE 1 CSA' }, { bookId: 58, tableName: 'TABLE 1 CSA' }, { bookId: 59, tableName: 'TABLE 1 CSA' },
  { bookId: 60, tableName: 'TABLE 1 CSA' }, { bookId: 61, tableName: 'TABLE 1 CSA' }, { bookId: 62, tableName: 'TABLE 1 CSA' },
  { bookId: 63, tableName: 'TABLE 1 CSA' }, { bookId: 64, tableName: 'TABLE 1 CSA' }, { bookId: 65, tableName: 'TABLE 1 CSA' },
  { bookId: 66, tableName: 'TABLE 1 CSA' }, { bookId: 67, tableName: 'TABLE 1 CSA' }, { bookId: 68, tableName: 'TABLE 1 CSA' },
  { bookId: 69, tableName: 'TABLE 1 CSA' }, { bookId: 70, tableName: 'TABLE 1 CSA' }, { bookId: 71, tableName: 'TABLE 1 CSA' },
  { bookId: 72, tableName: 'TABLE 1 CSA' }, { bookId: 73, tableName: 'TABLE 1 CSA' }, { bookId: 74, tableName: 'TABLE 1 CSA' },
  { bookId: 75, tableName: 'TABLE 1 CSA' }, { bookId: 76, tableName: 'TABLE 1 CSA' }, { bookId: 77, tableName: 'TABLE 1 CSA' },
  { bookId: 78, tableName: 'TABLE 1 CSA' }, { bookId: 79, tableName: 'TABLE 1 CSA' }, { bookId: 80, tableName: 'TABLE 1 CSA' },
  { bookId: 81, tableName: 'TABLE 1 CSA' }, { bookId: 82, tableName: 'TABLE 1 CSA' }, { bookId: 83, tableName: 'TABLE 1 CSA' },
  { bookId: 84, tableName: 'TABLE 1 CSA' }, { bookId: 85, tableName: 'TABLE 1 CSA' }, { bookId: 86, tableName: 'TABLE 1 CSA' },
  { bookId: 87, tableName: 'TABLE 1 CSA' }, { bookId: 88, tableName: 'TABLE 1 CSA' }, { bookId: 89, tableName: 'TABLE 1 CSA' },
  { bookId: 90, tableName: 'TABLE 1 ELT' }, { bookId: 91, tableName: 'TABLE 1 ELT' }, { bookId: 92, tableName: 'TABLE 1 ELT' },
  { bookId: 93, tableName: 'TABLE 1 ELT' }, { bookId: 94, tableName: 'TABLE 1 ELT' }, { bookId: 95, tableName: 'TABLE 1 ELT' },
  { bookId: 96, tableName: 'TABLE 1 ELT' }, { bookId: 97, tableName: 'TABLE 1 ETE' }, { bookId: 98, tableName: 'TABLE 1 ELT' },
  { bookId: 99, tableName: 'TABLE 1 ELT' }, { bookId: 125, tableName: 'TABLE 1 ELT' }, { bookId: 101, tableName: 'TABLE 1 ELT' },
  { bookId: 102, tableName: 'TABLE 1 ELT' }, { bookId: 103, tableName: 'TABLE 1 ELT' }, { bookId: 104, tableName: 'TABLE 1 ELT' },
  { bookId: 105, tableName: 'TABLE 1 ELT' }, { bookId: 106, tableName: 'TABLE 1 ELT' }, { bookId: 126, tableName: 'TABLE 1 ELT' },
  { bookId: 108, tableName: 'TABLE 1 ELT' }, { bookId: 109, tableName: 'TABLE 1 ELT' }, { bookId: 110, tableName: 'TABLE 1 ELT' },
  { bookId: 111, tableName: 'TABLE 1 ELT' }, { bookId: 112, tableName: 'TABLE 1 ELT' }, { bookId: 113, tableName: 'TABLE 1 ELT' },
  { bookId: 114, tableName: 'TABLE 1 ELT' }, { bookId: 117, tableName: 'TABLE 1 ELT' }, { bookId: 118, tableName: 'TABLE 1 ELT' },
  { bookId: 119, tableName: 'TABLE 1 ELT' }, { bookId: 120, tableName: 'TABLE 1 ELT' }, { bookId: 121, tableName: 'TABLE 1 ELT' },
  { bookId: 122, tableName: 'TABLE 1 ELT' }, { bookId: 123, tableName: 'TABLE 1 ELT' }, { bookId: 124, tableName: 'TABLE 1 ELT' },
  { bookId: 127, tableName: 'TABLE 1 ELT' }, { bookId: 128, tableName: 'TABLE 1 ELT' }, { bookId: 129, tableName: 'TABLE 1 ELT' },
  { bookId: 130, tableName: 'TABLE 1 ELT' }, { bookId: 131, tableName: 'TABLE 1 ELT' }, { bookId: 132, tableName: 'TABLE 1 ELT' },
  { bookId: 133, tableName: 'TABLE 1 ELT' }, { bookId: 134, tableName: 'TABLE 1 ELT' }, { bookId: 135, tableName: 'TABLE 1 ELT' },
  { bookId: 136, tableName: 'TABLE 1 ELT' }, { bookId: 137, tableName: 'TABLE 1 ETE' }, { bookId: 138, tableName: 'TABLE 1 ETE' },
  { bookId: 139, tableName: 'TABLE 1 ETE' }, { bookId: 140, tableName: 'TABLE 1 ETE' }, { bookId: 141, tableName: 'TABLE 1 ETE' },
  { bookId: 142, tableName: 'TABLE 1 ETE' }, { bookId: 143, tableName: 'TABLE 1 ETE' }, { bookId: 144, tableName: 'TABLE 1 ETE' },
  { bookId: 145, tableName: 'TABLE 1 ETE' }, { bookId: 146, tableName: 'TABLE 1 ETE' }, { bookId: 147, tableName: 'TABLE 1 ETE' },
  { bookId: 148, tableName: 'TABLE 1 ETE' }, { bookId: 149, tableName: 'TABLE 1 ETE' }, { bookId: 150, tableName: 'TABLE 1 ETE' },
  { bookId: 151, tableName: 'TABLE 1 ETE' }, { bookId: 152, tableName: 'TABLE 1 ETE' }, { bookId: 153, tableName: 'TABLE 1 ETE' },
  { bookId: 154, tableName: 'TABLE 1 ETE' }, { bookId: 155, tableName: 'TABLE 1 ETE' }, { bookId: 156, tableName: 'TABLE 1 ETE' },
  { bookId: 157, tableName: 'TABLE 1 ETE' }, { bookId: 158, tableName: 'TABLE 1 ETE' }, { bookId: 159, tableName: 'TABLE 1 ETE' },
  { bookId: 160, tableName: 'TABLE 1 ETE' }, { bookId: 161, tableName: 'TABLE 1 ETE' }, { bookId: 162, tableName: 'TABLE 1 ETE' },
  { bookId: 163, tableName: 'TABLE 1 ETE' }, { bookId: 164, tableName: 'TABLE 1 ETE' }, { bookId: 165, tableName: 'TABLE 1 ETE' },
  { bookId: 166, tableName: 'TABLE 1 ETE' }, { bookId: 167, tableName: 'TABLE 1 ETE' }, { bookId: 168, tableName: 'TABLE 1 ETE' },
  { bookId: 169, tableName: 'TABLE 1 ETE' }, { bookId: 170, tableName: 'TABLE 1 ETE' }, { bookId: 171, tableName: 'TABLE 1 ETE' },
  { bookId: 172, tableName: 'TABLE 1 ETE' }, { bookId: 173, tableName: 'TABLE 1 ETE' }, { bookId: 174, tableName: 'TABLE 1 ETE' },
  { bookId: 175, tableName: 'TABLE 1 ETE' }, { bookId: 176, tableName: 'TABLE 1 ETE' }, { bookId: 177, tableName: 'TABLE 1 ETE' },
  { bookId: 178, tableName: 'TABLE 1 ETE' }, { bookId: 179, tableName: 'TABLE 1 ETE' }, { bookId: 180, tableName: 'TABLE 1 ETE' },
  { bookId: 181, tableName: 'TABLE 1 ETE' }, { bookId: 182, tableName: 'TABLE 1 ETE' }, { bookId: 183, tableName: 'TABLE 1 ETE' },
  { bookId: 184, tableName: 'TABLE 1 ETE' }, { bookId: 185, tableName: 'TABLE 1 ETE' }, { bookId: 186, tableName: 'TABLE 1 ETE' },
  { bookId: 187, tableName: 'TABLE 1 ETE' }, { bookId: 188, tableName: 'TABLE 1 ETE' }, { bookId: 190, tableName: 'table 1 wot' },
  { bookId: 191, tableName: 'table 1 wot' }, { bookId: 192, tableName: 'table 1 wot' }, { bookId: 193, tableName: 'table 1 wot' },
  { bookId: 194, tableName: 'Table 1 wot' }, { bookId: 195, tableName: 'Table 1 wot' }, { bookId: 196, tableName: 'Table 1 wot' },
  { bookId: 197, tableName: 'Table 1 wot' }, { bookId: 198, tableName: 'Table 1 wot' }, { bookId: 199, tableName: 'Table 1 wot' },
  { bookId: 200, tableName: 'Table 1 wot' }, { bookId: 201, tableName: 'Table 1 wot' }, { bookId: 202, tableName: 'Table 1 wot' },
  { bookId: 203, tableName: 'Table 1 wot' }, { bookId: 204, tableName: 'Table 1 wot' }, { bookId: 205, tableName: 'Table 1 wot' },
  { bookId: 206, tableName: 'Table 1 wot' }, { bookId: 207, tableName: 'Table 1 wot' }, { bookId: 208, tableName: 'Table 1 wot' },
  { bookId: 209, tableName: 'Table 1 wot' }, { bookId: 210, tableName: 'Table 1 wot' }, { bookId: 211, tableName: 'Table 1 wot' },
  { bookId: 213, tableName: 'Table 1 wot' }, { bookId: 214, tableName: 'Table 1 wot' }, { bookId: 215, tableName: 'Table 1 wot' },
  { bookId: 216, tableName: 'Table 1 wot' }, { bookId: 217, tableName: 'Table 1 wot' }, { bookId: 218, tableName: 'Table 1 wot' },
  { bookId: 219, tableName: 'Table 1 wot' }, { bookId: 220, tableName: 'Table 1 wot' }, { bookId: 221, tableName: 'Table 1 wot' },
  { bookId: 222, tableName: 'Table 1 wot' }, { bookId: 223, tableName: 'Table 1 wot' }, { bookId: 224, tableName: 'Table 1 wot' },
  { bookId: 225, tableName: 'Table 1 wot' }, { bookId: 226, tableName: 'Table 1 wot' }, { bookId: 227, tableName: 'Table 1 wot' },
  { bookId: 228, tableName: 'Table 1 wot' }, { bookId: 229, tableName: 'Table 1 wot' }, { bookId: 230, tableName: 'TABLE 1 PWO' },
  { bookId: 231, tableName: 'TABLE 1 PWO' }, { bookId: 232, tableName: 'TABLE 1 PWO' }, { bookId: 233, tableName: 'TABLE 1 PWO' },
  { bookId: 234, tableName: 'TABLE 1 PWO' }, { bookId: 235, tableName: 'TABLE 1 PWO' }, { bookId: 236, tableName: 'TABLE 1 PWO' },
  { bookId: 237, tableName: 'TABLE 1 PWO' }, { bookId: 238, tableName: 'TABLE 1 PWO' }, { bookId: 239, tableName: 'TABLE 1 PWO' },
  { bookId: 240, tableName: 'TABLE 1 PWO' }, { bookId: 241, tableName: 'Table 1 PWO' }, { bookId: 242, tableName: 'TABLE 1 PWO' },
  { bookId: 243, tableName: 'TABLE 1 PWO' }, { bookId: 244, tableName: 'TABLE 1 PWO' }, { bookId: 245, tableName: 'TABLE 1 PWO' },
  { bookId: 246, tableName: 'TABLE 1 PWO' }, { bookId: 247, tableName: 'TABLE 1 PWO' }, { bookId: 248, tableName: 'TABLE 1 PWO' },
  { bookId: 249, tableName: 'TABLE 1 LSV' }, { bookId: 250, tableName: 'TABLE 1 LSV' }, { bookId: 251, tableName: 'TABLE 1 LSV' },
  { bookId: 262, tableName: 'TABLE 1 LSV' }, { bookId: 253, tableName: 'TABLE 1 LSV' }, { bookId: 261, tableName: 'TABLE 1 LSV' },
  { bookId: 255, tableName: 'PAVEMENT' }, { bookId: 259, tableName: 'TABLE 1 LSV' }, { bookId: 260, tableName: 'TABLE 1 LSV' },
  { bookId: 263, tableName: 'TABLE 1 LSV' }, { bookId: 264, tableName: 'TABLE 1 LSV' }, { bookId: 265, tableName: 'TABLE 1 LSV' },
  { bookId: 266, tableName: 'TABLE 1 LSV' }, { bookId: 267, tableName: 'TABLE 1 LSV' }, { bookId: 268, tableName: 'TABLE 1 LSV' },
  { bookId: 269, tableName: 'TABLE 1 LSV' }, { bookId: 270, tableName: 'TABLE 1 LSV' }, { bookId: 271, tableName: 'TABLE 1 LSV' },
  { bookId: 272, tableName: 'TABLE 1 LSV' }, { bookId: 273, tableName: 'TABLE 1 LSV' }, { bookId: 274, tableName: 'TABLE 1 LSV' },
  { bookId: 275, tableName: 'TABLE 1 LSV' }, { bookId: 276, tableName: 'TABLE 1 LSV' }, { bookId: 277, tableName: 'TABLE 1 LSV' },
  { bookId: 278, tableName: 'TABLE 1 LSV' }, { bookId: 279, tableName: 'TABLE 1 LSV' }, { bookId: 280, tableName: 'TABLE 1 LSV' },
  { bookId: 281, tableName: 'TABLE 1 LSV' }, { bookId: 282, tableName: 'TABLE 1 LSV' }, { bookId: 283, tableName: 'TABLE 1 LSV' },
  { bookId: 284, tableName: 'TABLE 1 LSV' }, { bookId: 285, tableName: 'TABLE 1 LSV' }, { bookId: 286, tableName: 'TABLE 1 LSV' },
  { bookId: 287, tableName: 'TABLE 1 LSV' }, { bookId: 288, tableName: 'TABLE 1 LSV' }, { bookId: 289, tableName: 'TABLE 1 LSV' },
  { bookId: 290, tableName: 'TABLE 1 LSV' }, { bookId: 291, tableName: 'TABLE 2 BDC' }, { bookId: 292, tableName: 'TABLE 1 LSV' },
  { bookId: 293, tableName: 'TABLE 1 LSV' }, { bookId: 294, tableName: 'TABLE 2 BDC' }, { bookId: 295, tableName: 'TABLE 2 BDC' },
  { bookId: 296, tableName: 'TABLE 2 BDC' }, { bookId: 297, tableName: 'TABLE 2 BDC' }, { bookId: 298, tableName: 'TABLE 2 BDC' },
  { bookId: 299, tableName: 'TABLE 2 BDC' }, { bookId: 300, tableName: 'TABLE 2 BDC' }, { bookId: 301, tableName: 'TABLE 2 BDC' },
  { bookId: 302, tableName: 'TABLE 2 BDC' }, { bookId: 303, tableName: 'TABLE 2 BDC' }, { bookId: 304, tableName: 'TABLE 2 BDC' },
  { bookId: 305, tableName: 'TABLE 2 BDC' }, { bookId: 306, tableName: 'TABLE 2 BDC' }, { bookId: 307, tableName: 'TABLE 2 BDC' },
  { bookId: 308, tableName: 'TABLE 2 BDC' }, { bookId: 309, tableName: 'TABLE 2 BDC' }, { bookId: 310, tableName: 'TABLE 2 BDC' },
  { bookId: 311, tableName: 'TABLE 2 BDC' }, { bookId: 312, tableName: 'TABLE 2 BDC' }, { bookId: 313, tableName: 'TABLE 2 BDC' },
  { bookId: 314, tableName: 'TABLE 2 BDC' }, { bookId: 315, tableName: 'TABLE 2 BDC' }, { bookId: 316, tableName: 'TABLE 2 BDC' },
  { bookId: 317, tableName: 'TABLE 2 BDC' }, { bookId: 318, tableName: 'TABLE 2 BDC' }, { bookId: 319, tableName: 'TABLE 2 BDC' },
  { bookId: 320, tableName: 'TABLE 2 BDC' }, { bookId: 321, tableName: 'TABLE 2 BDC' }, { bookId: 322, tableName: 'TABLE 2 BDC' },
  { bookId: 323, tableName: 'TABLE 2 BDC' }, { bookId: 324, tableName: 'TABLE 2 BDC' }, { bookId: 325, tableName: 'TABLE 2 BDC' },
  { bookId: 326, tableName: 'TABLE 2 BDC' }, { bookId: 327, tableName: 'TABLE 2 BDC' }, { bookId: 328, tableName: 'TABLE 2 BDC' },
  { bookId: 329, tableName: 'TABLE 2 BDC' }, { bookId: 330, tableName: 'TABLE 2 BDC' }, { bookId: 331, tableName: 'TABLE 2 BDC' },
  { bookId: 332, tableName: 'TABLE 2 BDC' }, { bookId: 333, tableName: 'TABLE 2 BDC' }, { bookId: 334, tableName: 'TABLE 2 BDC' },
  { bookId: 335, tableName: 'TABLE 2 BDC' }, { bookId: 336, tableName: 'TABLE 2 BDC' }, { bookId: 337, tableName: 'TABLE 2 BDC' },
  { bookId: 338, tableName: 'TABLE 2 BDC' }, { bookId: 339, tableName: 'TABLE 2 BDC' }, { bookId: 340, tableName: 'TABLE 2 BDC' },
  { bookId: 341, tableName: 'TABLE 2 BDC' }, { bookId: 342, tableName: 'TABLE 2 BDC' }, { bookId: 343, tableName: 'TABLE 2 BDC' },
  { bookId: 344, tableName: 'TABLE 2 BDC' }, { bookId: 345, tableName: 'TABLE 2 BDC' }, { bookId: 346, tableName: 'TABLE 2 BDC' },
  { bookId: 347, tableName: 'TABLE 2 BDC' }, { bookId: 348, tableName: 'TABLE 2 BDC' }, { bookId: 349, tableName: 'TABLE 2 BDC' },
  { bookId: 350, tableName: 'TABLE 2 BDC' }, { bookId: 351, tableName: 'TABLE 2 BDC' }, { bookId: 352, tableName: 'TABLE 2 BDC' },
  { bookId: 353, tableName: 'TABLE 2 BDC' }, { bookId: 354, tableName: 'TABLE 2 BDC' }, { bookId: 355, tableName: 'TABLE 2 BDC' },
  { bookId: 356, tableName: 'TABLE 2 BDC' }, { bookId: 357, tableName: 'TABLE 2 BDC' }, { bookId: 358, tableName: 'TABLE 2 BDC' },
  { bookId: 359, tableName: 'TABLE 2 BDC' }, { bookId: 360, tableName: 'TABLE 2 BDC' }, { bookId: 361, tableName: 'TABLE 2 BDC' },
  { bookId: 362, tableName: 'TABLE 2 BDC' }, { bookId: 363, tableName: 'TABLE 2 BDC' }, { bookId: 364, tableName: 'TABLE 2 BDC' },
  { bookId: 365, tableName: 'TABLE 2 BDC' }, { bookId: 366, tableName: 'TABLE 2 BDC' }, { bookId: 367, tableName: 'TABLE 2 BDC' },
  { bookId: 368, tableName: 'TABLE 2 BDC' }, { bookId: 369, tableName: 'TABLE 2 BDC' }, { bookId: 370, tableName: 'TABLE 2 BDC' },
  { bookId: 372, tableName: 'TABLE 2 BDC' }, { bookId: 373, tableName: 'TABLE 2 BDC' }, { bookId: 374, tableName: 'TABLE 2 BDC' },
  { bookId: 375, tableName: 'TABLE 2 BDC' }, { bookId: 376, tableName: 'TABLE 2 BDC' }, { bookId: 377, tableName: 'TABLE 2 BDC' },
  { bookId: 379, tableName: 'TABLE 2 BDC' }, { bookId: 380, tableName: 'TABLE 2 BDC' }, { bookId: 381, tableName: 'TABLE 2 BDC' },
  { bookId: 382, tableName: 'TABLE 2 BDC' }, { bookId: 383, tableName: 'TABLE 2 BDC' }, { bookId: 384, tableName: 'TABLE 2 BDC' },
  { bookId: 385, tableName: 'TABLE 2 BDC' }, { bookId: 386, tableName: 'TABLE 2 BDC' }, { bookId: 387, tableName: 'TABLE 2 BDC' },
  { bookId: 388, tableName: 'TABLE 2 BDC' }, { bookId: 389, tableName: 'TABLE 2 BDC' }, { bookId: 390, tableName: 'TABLE 2 BDC' },
  { bookId: 391, tableName: 'TABLE 2 BDC' }, { bookId: 392, tableName: 'TABLE 2 BDC' }, { bookId: 393, tableName: 'TABLE 2 BDC' },
  { bookId: 394, tableName: 'TABLE 2 BDC' }, { bookId: 395, tableName: 'TABLE 2 BDC' }, { bookId: 396, tableName: 'TABLE 2 BDC' },
  { bookId: 397, tableName: 'TABLE 2 BDC' }, { bookId: 398, tableName: 'TABLE 2 BDC' }, { bookId: 399, tableName: 'TABLE 2 BDC' },
  { bookId: 400, tableName: 'TABLE 2 BDC' }, { bookId: 401, tableName: 'TABLE 2 BDC' }, { bookId: 402, tableName: 'TABLE 2 BDC' }
];

const studentsData = [
  { studentName: 'habakubaho cedrick', class: 'software development', phonenumber: '0781668988', nesaCode: '110405000000' },
  { studentName: 'mugisha', class: 'sod', phonenumber: '0783672536561', nesaCode: '123456000000', level: 'level4' },
  { studentName: 'AMANI Moussa', class: 'LVS', nesaCode: '330306190400' },
  { studentName: 'BERWA GISUBISO Marcellin', class: 'LVS', nesaCode: '310501220006' },
  { studentName: 'DUSHIMUMUKIZA ABBE Janvier', class: 'LVS', nesaCode: '320403220699' },
  { studentName: 'HIRWA NDUWUMUREMYI James', class: 'LVS', nesaCode: '210116150393' },
  { studentName: 'IGIHOZO AIMEE Gladys', class: 'LVS', nesaCode: '000000000000' },
  { studentName: 'IRAKOZE NGARAMBE calvin', class: 'LVS', nesaCode: '570405200451' },
  { studentName: 'IGIHOZO AIMEE Gladys', class: 'LVS', nesaCode: '323410030000' },
  { studentName: 'ISHIMWE Fabrice', class: 'LVS', nesaCode: '510104220098' },
  { studentName: 'ISHIMWE MUTAMBA Kevine', class: 'LVS', nesaCode: '551002190557' },
  { studentName: 'KARANGWA ISHIMWE Polycarpe', class: 'LVS', nesaCode: '271202220005' },
  { studentName: 'UWERA BYIRINGIRO Marie Reine', class: 'LVS', nesaCode: '250206200120' },
  { studentName: 'UWIMANA Innocent', class: 'LVS', nesaCode: '120708180709' }
];

const teachersData = [
  { teacherName: 'irumva hirwa moses', subject: 'data structure', phone: '0785367290', identityNumber: '1234567891234567' }
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    // Clear all data
    await Promise.all([
      SuperAdmin.deleteMany({}), School.deleteMany({}), Librarian.deleteMany({}),
      Book.deleteMany({}), Student.deleteMany({}), Teacher.deleteMany({}),
      BookAllocation.deleteMany({})
    ]);
    console.log('Cleared existing data');

    // Super Admin
    const superAdmin = await SuperAdmin.create({
      email: 'superadmin@gmail.com',
      password: await bcrypt.hash('superadmin@2026', 10)
    });
    console.log('Created super admin');

    // Demo School
    const school = await School.create({
      name: 'Ecole Technique Saint Kizito Save TSS',
      type: 'tvet',
      district: 'Gisagara',
      sector: 'Save',
      phone: '0781668988',
      email: 'info@ectsave.rw',
      adminName: 'Admin Librarian',
      status: 'active'
    });
    console.log('Created demo school');

    // School Admin (Librarian)
    await Librarian.create({
      name: 'Admin Librarian',
      email: 'admin@gmail.com',
      password: await bcrypt.hash('admin@2026', 10),
      school: school._id
    });
    console.log('Created school admin');

    // Books
    const bookDocs = await Book.insertMany(
      booksData.map(b => ({ ...b, quantity: 1, available: 1, school: school._id }))
    );
    console.log(`Inserted ${bookDocs.length} books`);

    // Build oldId -> newId mapping
    // The SQL IDs start from 3 (in the data). We need to map them to the MongoDB insertion order.
    // The booksData array has 402 entries. MongoDB will assign _id in order.
    // The SQL data has sequential IDs but some gaps. Let's map based on index + 3 offset.
    // Actually, looking more carefully, the booksData array preserves the original order from the SQL.
    // The SQL IDs for the first entries: 3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,24,21,23,25,26,27,28,29,30,31,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52...
    // These don't follow a simple pattern. The allocations reference these old IDs.
    // Let me create a map by matching on isbn + title since that's more reliable.

    // Actually, since we inserted in the same order as the SQL dump, and the SQL had sequential-ish IDs,
    // we can map by index. But the SQL IDs have gaps. Let me create the mapping based on array index.
    // The first book in the array had SQL id=3, second had id=4, etc.
    // Actually, the SQL dump goes: id=3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,24,21,23,25,26,27,28...
    // Hmm, that's not sequential. Let me just match by isbn+title combination.
    // Better approach: create a map from old SQL id to MongoDB _id

    // The books in the SQL are inserted in this order with these IDs:
    const sqlBookIds = [3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,24,21,23,25,26,27,28,29,30,31,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,101,102,103,104,105,106,108,109,110,111,112,113,114,126,125,117,118,119,120,121,122,123,124,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,262,253,261,255,259,260,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,372,373,374,375,376,377,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402];

    const idMap = {};
    sqlBookIds.forEach((oldId, idx) => {
      idMap[oldId] = bookDocs[idx]._id;
    });

    // Students
    const studentDocs = [];
    for (const s of studentsData) {
      const student = await Student.create({
        ...s, password: await bcrypt.hash('changeme', 10), school: school._id
      });
      studentDocs.push(student);
    }
    console.log(`Inserted ${studentDocs.length} students`);

    // Teacher
    for (const t of teachersData) {
      await Teacher.create({
        ...t, password: await bcrypt.hash('changeme', 10), school: school._id
      });
    }
    console.log('Inserted 1 teacher');

    // Allocations
    const allocDocs = allocationsData.map(a => ({
      book: idMap[a.bookId],
      tableName: a.tableName,
      school: school._id
    })).filter(a => a.book != null);
    await BookAllocation.insertMany(allocDocs);
    console.log(`Inserted ${allocDocs.length} allocations`);

    console.log('\n✅ Seed completed successfully!');
    console.log(`  Super Admin: superadmin@gmail.com / superadmin@2026`);
    console.log(`  School Admin: admin@gmail.com / admin@2026`);
    console.log(`  Students default password: changeme`);
    console.log(`  Teachers default password: changeme`);

    process.exit(0);
  } catch (err) {
    console.error('Seed error:', err);
    process.exit(1);
  }
}

seed();
